### ISSUE TITLE
Is this controlling on a PC?

### ISSUE THREAD

**Issue by Multimegamander** [RattletraPM/NTRRemoteplaySimulator#1]

**Comment by RattletraPM** [comment]
Sorry if I didn't reply right away but you were so quick to post this yesterday that I didn't even have time to initialize the repo correctly! (It was very late too, so I got away as soon as I did)

Anyways, no - what you're looking for is InputRedirection. Luma has that feature built in and you can use any compatible client on your PC (such as [InputRedirectionClient-Qt](https://github.com/TuxSH/InputRedirectionClient-Qt) ) to control your 3DS via your PC.

This script right here, on the other hand, just simulates a 3DS streaming frames via NTR. It's nearly useless for end users but may be a bit useful to developers. You can see it in action (and also understand why I made it) [in the latest Snickerstream vlog](https://www.youtube.com/watch?v=cyaGBJrANfk).

**Comment by Multimegamander** [comment]
I watched it the moment you posted it, then went to bed, but neat :)
